apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ingredients-hpa
  namespace: recipe-app
  labels:
    app: ingredients-service
    app.kubernetes.io/name: ingredients-hpa
    app.kubernetes.io/part-of: recipe-collection-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingredients-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
