apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: recipe-app
  labels:
    app.kubernetes.io/name: postgres-pvc
    app.kubernetes.io/part-of: recipe-collection-system
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
